#!/usr/bin/env bash
set -euo pipefail

# 05_run_go_analysis.sh
# Purpose: annotate peak sets to nearest genes and run GO:BP enrichment.
# Inputs are the peak sets generated by the reciprocal liftover workflow.
#
# Usage:
#   bash workflow/scripts/05_run_go_analysis.sh /path/to/python /path/to/results /path/to/resources

usage(){
  echo "Usage: $0 PYTHON_BIN RESULTS_DIR RESOURCES_DIR"
  exit 1
}

if [ $# -ne 3 ]; then
  usage
fi

PYTHON_BIN="$1"
RESULTS_DIR="$2"
RESOURCES_DIR="$3"
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

PEAK_DIR="$RESULTS_DIR/peak_sets"
GO_DIR="$RESULTS_DIR/go_analysis"
ANNOT_DIR="$GO_DIR/annotations"
GENE_DIR="$GO_DIR/gene_lists"
ENRICH_DIR="$GO_DIR/enrichment"
GTF_DIR="$RESOURCES_DIR/annotations"

mkdir -p "$ANNOT_DIR" "$GENE_DIR" "$ENRICH_DIR" "$GTF_DIR"

HUMAN_GTF="$GTF_DIR/gencode.v44.annotation.gtf.gz"
MOUSE_GTF="$GTF_DIR/gencode.vM25.annotation.gtf.gz"

if [ ! -f "$HUMAN_GTF" ]; then
  curl -L -o "$HUMAN_GTF" https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_44/gencode.v44.annotation.gtf.gz
fi

if [ ! -f "$MOUSE_GTF" ]; then
  curl -L -o "$MOUSE_GTF" https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.annotation.gtf.gz
fi

annotate_one(){
  local peaks="$1"
  local gtf="$2"
  local label="$3"

  "$PYTHON_BIN" "$SCRIPT_DIR/annotate_peaks_to_nearest_genes.py" \
    --peaks "$peaks" \
    --gtf "$gtf" \
    --out-tsv "$ANNOT_DIR/${label}.annotated.tsv" \
    --out-genes "$GENE_DIR/${label}.genes.txt"
}

run_go_one(){
  local gene_list="$1"
  local organism="$2"
  local label="$3"

  "$PYTHON_BIN" "$SCRIPT_DIR/run_go_gprofiler.py" \
    --genes "$gene_list" \
    --organism "$organism" \
    --label "$label" \
    --outdir "$ENRICH_DIR"
}

annotate_one "$PEAK_DIR/human_conserved_by_sequence.bed" "$HUMAN_GTF" "human_shared"
annotate_one "$PEAK_DIR/human_species_specific.bed" "$HUMAN_GTF" "human_specific"
annotate_one "$PEAK_DIR/mouse_conserved_by_sequence.bed" "$MOUSE_GTF" "mouse_shared"
annotate_one "$PEAK_DIR/mouse_species_specific.bed" "$MOUSE_GTF" "mouse_specific"

run_go_one "$GENE_DIR/human_shared.genes.txt" hsapiens human_shared
run_go_one "$GENE_DIR/human_specific.genes.txt" hsapiens human_specific
run_go_one "$GENE_DIR/mouse_shared.genes.txt" mmusculus mouse_shared
run_go_one "$GENE_DIR/mouse_specific.genes.txt" mmusculus mouse_specific

echo "GO analysis finished. Results are in: $GO_DIR"
